name: lymphomamilbenchmark
channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - ffmpeg=4.3
  - filelock=3.17.0
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - h5py=3.12.1
  - hdf5=1.14.5
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.0.30
  - libcurand=10.3.10.19
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.4.2
  - numexpr=2.10.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.1
  - propcache=0.3.1
  - psutil=5.9.0
  - pyg=2.5.2
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - dgl==2.1.0
      - einops==0.8.1
      - imageio==2.37.0
      - numpy==1.26.4
      - nystrom-attention==0.0.14
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - torchdata==0.7.0
      - typing-inspection==0.4.0
